### ISSUE TITLE
AttributeError: 'module' object has no attribute 'top_block_gui'

### ISSUE THREAD

**Issue by K4KDR** [andrepuschmann/gr-cc11xx#4]
Hello!

Having searched online for a generic answer to this (without success), any idea why I get the following when running the **file_source_test.grc** flowgraph:

```
Traceback (most recent call last):
  File "/home/k4kdr/gr-cc11xx/examples/modified/top_block.py", line 39, in <module>
    class top_block(grc_wxgui.top_block_gui):
AttributeError: 'module' object has no attribute 'top_block_gui'
```

System Information:
-Ubuntu 16.04 64-bit
-Python2 version 2.7.12
-GNU Radio version 3.7.9

FYI, the cmake/make/sudo make install/sudo ldconfig steps all completed without any error or warning messages.

Many thanks!

**Comment by andrepuschmann** [comment]
I am afraid I can't help you with that. Probably best to ask the GNU Radio guys.
